# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Sass Build
        # You may pin to the exact commit or the version.
        # uses: gha-utilities/sass-build@d16a98ec3a5a8abd4581ee48128516689a5dba98
        uses: gha-utilities/sass-build@v0.4.5
        with:
          # Relative path(s) to SASS or SCSS file, eg. _scss/main.scss
          source: ~/scss/style.scss
          # Path(s) compiled CSS should be saved, eg. ~/workspace_sass/assets/css/main.css
          destination: ~/css/style.min.css
          # Array (Action splits on ":"), of directories to look under for imports and used modules
          includePaths: true # optional
          # String, either "expanded", "compressed", "nested", "compact"; defaults to "compressed"
          outputStyle: compressed# optional
          # Integer and float precision when compiling CSS, eg. `20`
          precision: tab # optional
          # String, either "space" or "tab", default "space"
          indentType: 2 # optional
          # Integer, of tabs/spaces used to indent, eg. `1`
          indentWidth: 2 # optional, default is 2
          # String, either "lf", "lfcr", "cr", or "crlf", default "lf"
          linefeed: false # optional
          # Boolean, default `false` if `true` emits comments where CSS was compiled from
          sourceComments: false # optional
          # May be boolean or string, see https://sass-lang.com/documentation/js-api#sourcemap
          sourceMap: false # optional
          # Boolean, when `true` compiled CSS is not linked to source map
          omitSourceMapUrl: false # optional
          # Boolean, when `true` embeds contents of Sass files that contributed to compiled CSS
          sourceMapContents: false # optional
          # Boolean, when `true` embeds source map within compiled CSS
          sourceMapEmbed: false # optional
          # String, prepended to all links from from source map to Sass files
          sourceMapRoot: false # optional
          # Outputs render_options used for compiling CSS
          debug: false # optional
          
      - name: Sass Build Done
        run: echo Done building sass files.
