# This is a basic workflow to help you get started with Actions

name: Sass Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Sass Build
        # You may pin to the exact commit or the version.
        # uses: gha-utilities/sass-build@d16a98ec3a5a8abd4581ee48128516689a5dba98
        uses: gha-utilities/sass-build@v0.4.5
        with:
          # Relative path(s) to SASS or SCSS file, eg. _scss/main.scss
          source: scss/style.scss
          # Path(s) compiled CSS should be saved, eg. ~/workspace_sass/assets/css/main.css
          destination: ./css/style.min.css
          # Array (Action splits on ":"), of directories to look under for imports and used modules
          includePaths: true
          # String, either "expanded", "compressed", "nested", "compact"; defaults to "compressed"
          outputStyle: compressed
          # May be boolean or string, see https://sass-lang.com/documentation/js-api#sourcemap
          sourceMap: false
          # Outputs render_options used for compiling CSS
          debug: false
